services:
  db:
    image: postgres:15
    container_name: latsar_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      # 🟢 mount data directory (menyimpan isi database)
      - postgres_data:/var/lib/postgresql/data
      # 🟢 tambahkan baris di bawah ini untuk menjalankan init_db.sql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  backend:
    build: ./backend
    container_name: latsar_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  postgres_data: